// components/header.vue
<script setup lang="ts">
    import { siteConfig } from "~/config/site";
    import { navMenu } from "~/config/menu";
    const route = useRoute();
</script>
<template>
    <header class="bg-white">
      <div class="mx-auto max-w-screen-xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-16 items-center justify-between">
          <div class="flex-1 md:flex md:items-center md:gap-12">
            <nuxt-link class="block text-teal-600" v-bind:title="siteConfig.name" href="/">
              <span class="sr-only">Home</span>
              <img src="/images/beaker-dark.png" width="35" height="35" class="hover:opacity-75" />
            </nuxt-link>
          </div>
          <div class="md:flex md:items-center md:gap-12">
            <nav aria-label="Global" class="hidden md:block">
              <ul class="flex items-center gap-6 text-sm">
                <li v-for="(item, index) in navMenu.nav" :key="index">
                    <nuxt-link v-bind:to="item.href" class="transition hover:text-gray-500/75" :style="{'color': route.path === item.href ? '#00219a' : '#858585'}">
                        {{ item.label }}
                    </nuxt-link>
                </li>
              </ul>
            </nav>
            <div class="flex items-center gap-4">
              <div class="sm:flex sm:gap-4">
                <nuxt-link
                    class="inline-block rounded-full bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 p-[2px] hover:text-white focus:outline-none focus:ring ring-red-400 active:text-opacity-75"
                    href="/login"
                >
                    <span
                    class="block rounded-full bg-white px-8 py-3 text-sm font-medium hover:bg-transparent"
                    >
                    Login
                    </span>
                </nuxt-link>
              </div>
              <div class="sm:flex sm:gap-4">
                <nuxt-link href="/register" class="btn btn-secondary rounded-full">
                    Join
                </nuxt-link>
              </div>
              <div class="block md:hidden">
                <button
                  class="rounded bg-gray-100 p-2 text-gray-600 transition hover:text-gray-600/75"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    stroke-width="2"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M4 6h16M4 12h16M4 18h16"
                    />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
  </template>

// src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { NavigationEnd, Router } from '@angular/router';

import { Config } from 'fire-ng/lib/interfaces/config';
import { Layout } from 'fire-ng/lib/interfaces/layout';

import { AppService } from 'src/app/shared/app.service';

@Component({
  selector: 'blz-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  public app: Config;
  public site: Layout;

  burgerVisible: boolean;

  constructor(appService: AppService, private router: Router) { 
    const config = appService.getConfig();
    this.app = config.app;
    this.site = config.site;
    this.burgerVisible = config.site.burgerVisible;
    router.events.subscribe((val) => {
      // close menu on route change
      this.burgerVisible = false;  
    });
  }

  ngOnInit(): void {
  }

}


<div class="px-4 py-3 text-gray-100 bg-indigo-600">
  <div class="text-sm font-medium text-center">
    The One Solution is <span class="hidden md:inline">a selection of services</span> offered by <a class="hover:underline" href="https://blazed.company/" target="_blank">Blazed Labs LLC</a>.
  </div>
</div>
<div class="header text-gray-600 body-font shadow-md">
  <nav class="grid grid-cols-2 header-nav">
    <div class="col-start-1">
      <a routerLink="/home" title="{{ app.title }}" class="flex hover:opacity-75 title-font font-medium items-center text-gray-900 mb-4 ml-20 md:mt-7 md:mb-0 header-logo">
        <img src="{{ site.logo }}?w=75&h=75">
      </a>
    </div>
    <div class="header-nav-links col-start-4 md:mt-7 md:mb-5 md:mr-20">
      <app-nav></app-nav>
    </div>
  </nav>
  <nav class="header-nav-mobile pt-5 bg-gray-200 grid grid-cols-2 w-full">
      <div class="header-nav-burge py-5 mt-2 w-half relative mx-auto">
        <a routerLink="/home">
          <img class="w-50 h-50" src="https://blazed.sirv.com/logo/Beaker-Dark.png?w=50&h=50">
        </a>
      </div>
      <div class="text-center py-5 mt-1">
        <button class="mx-auto" (click)="burgerVisible=!burgerVisible">
          <ng-container *ngIf="burgerVisible">
            <svg width="60" height="60" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.646 5.646a.5.5 0 000 .708l8 8a.5.5 0 00.708-.708l-8-8a.5.5 0 00-.708 0z" clip-rule="evenodd"/>
              <path fill-rule="evenodd" d="M14.354 5.646a.5.5 0 010 .708l-8 8a.5.5 0 01-.708-.708l8-8a.5.5 0 01.708 0z" clip-rule="evenodd"/>
            </svg>
          </ng-container>
          <ng-container *ngIf="!burgerVisible">
            <svg width="60" height="60" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.5 13.5A.5.5 0 015 13h10a.5.5 0 010 1H5a.5.5 0 01-.5-.5zm0-4A.5.5 0 015 9h10a.5.5 0 010 1H5a.5.5 0 01-.5-.5zm0-4A.5.5 0 015 5h10a.5.5 0 010 1H5a.5.5 0 01-.5-.5z" clip-rule="evenodd"/>
            </svg>
          </ng-container>
        </button>
      </div>
    <ng-container *ngIf="burgerVisible">
      <div class="col-start-1 col-end-7 header-nav-links-mobile bg-gray-200 absolute top-40 w-full h-screen pt-10">
        <app-nav></app-nav>
      </div>
    </ng-container>
  </nav>
</div>
